const $=id=>document.getElementById(id),S={c:[],e:new Map(),i:0,last:0,guide:false,info:false,h:null,ph:null};
const clock=d=>(d||new Date()).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function m3u(t,n){let a=[],m;for(let l of t.split(/\r?\n/)){l=l.trim();if(l.startsWith('#EXTINF')){m={};for(let x of l.matchAll(/([\w-]+)="([^"]*)"/g))m[x[1]]=x[2];let i=l.indexOf(',');m.name=i>0?l.slice(i+1).trim():'Channel'}else if(l&&!l.startsWith('#')&&m){a.push({id:m['tvg-id']||m.name,name:m.name,url:l});m=null;if(a.length>=n)break}}return a}
function xd(s){if(!s)return null;let m=s.match(/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/);return m?new Date(Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+m[6])):new Date(s)}
function epg(t){let d=new DOMParser().parseFromString(t,'application/xml'),m=new Map();for(let p of d.querySelectorAll('programme')){let id=p.getAttribute('channel'),s=xd(p.getAttribute('start')),e=xd(p.getAttribute('stop'));if(!id||!s||!e)continue;let q={start:s,stop:e,title:p.querySelector('title')?.textContent||'Programming',desc:p.querySelector('desc')?.textContent||''};if(!m.has(id))m.set(id,[]);m.get(id).push(q)}return m}
function prog(c){let a=S.e.get(c.id)||[],t=new Date();return a.find(x=>x.start<=t&&x.stop>t)||a[0]}
function render(){ $('clock').textContent=clock();$('day').textContent=new Date().toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'}).toUpperCase();let r=$('rows');r.innerHTML='';S.c.slice(0,8).forEach((c,i)=>{let p=prog(c),x=document.createElement('div');x.className='row '+(i===S.i?'sel':'');x.innerHTML=`<div class=num>${String(i+1).padStart(3,'0')}</div><div><div class=name>${esc(c.name)}</div><div class=prog>${esc(p?.title||'PROGRAM INFORMATION UNAVAILABLE')}</div></div>`;x.onclick=()=>{S.i=i;render();preview()};r.appendChild(x)});preview()}
function preview(){let c=S.c[S.i];if(!c)return;let p=prog(c);$('pchan').textContent=`${String(S.i+1).padStart(3,'0')} ${c.name}`;$('ptitle').textContent=p?.title||c.name;$('pdesc').textContent=p?.desc||'Press OK to tune.';if(!c.url)return;try{if(Hls?.isSupported()){if(S.ph)S.ph.destroy();S.ph=new Hls;S.ph.loadSource(c.url);S.ph.attachMedia($('preview'));S.ph.on(Hls.Events.MANIFEST_PARSED,()=>$('preview').play().catch(()=>{}))}else{$('preview').src=c.url;$('preview').play().catch(()=>{})}}catch(e){}}
function banner(){let c=S.c[S.i],p=prog(c);$('bnum').textContent=String(S.i+1).padStart(3,'0');$('bname').textContent=c.name;$('btitle').textContent=p?.title||'Digital Cable';$('btime').textContent=clock();$('banner').classList.remove('hidden');clearTimeout(S.bt);S.bt=setTimeout(()=>$('banner').classList.add('hidden'),4000)}
function tune(i){if(!S.c.length)return;S.last=S.i;S.i=Math.max(0,Math.min(S.c.length-1,i));let c=S.c[S.i];$('guide').classList.add('hidden');S.guide=false;try{if(S.h)S.h.destroy();if(c.url&&Hls?.isSupported()){S.h=new Hls;S.h.loadSource(c.url);S.h.attachMedia($('video'));S.h.on(Hls.Events.MANIFEST_PARSED,()=>$('video').play().catch(()=>{}))}else if(c.url){ $('video').src=c.url;$('video').play().catch(()=>{})}}catch(e){}banner()}
function openInfo(){let c=S.c[S.i],p=prog(c);$('iname').textContent=`${String(S.i+1).padStart(3,'0')} ${c.name}`;$('ititle').textContent=p?.title||'Digital Cable';$('imeta').textContent=p?`${clock(p.start)} - ${clock(p.stop)}`:'';$('idesc').textContent=p?.desc||'No program description is available.';$('info').classList.remove('hidden');S.info=true;clearTimeout(S.it);S.it=setTimeout(closeInfo,7000)}function closeInfo(){$('info').classList.add('hidden');S.info=false}
function key(k){if(S.info){if(k==='exit'||k==='info')closeInfo();return}if(k==='guide'){S.guide=!S.guide;$('guide').classList.toggle('hidden',!S.guide);if(S.guide)render();return}if(k==='info')return openInfo();if(k==='exit'){$('guide').classList.add('hidden');S.guide=false;return}if(k==='up')return S.guide?(S.i=Math.max(0,S.i-1),render()):tune(S.i-1);if(k==='down')return S.guide?(S.i=Math.min(S.c.length-1,S.i+1),render()):tune(S.i+1);if(k==='channelup')return tune(S.i+1);if(k==='channeldown')return tune(S.i-1);if(k==='last')return tune(S.last);if(k==='ok')return S.guide?tune(S.i):banner()}
addEventListener('keydown',e=>{let m={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',Enter:'ok',Escape:'exit',g:'guide',i:'info',l:'last'};if(m[e.key])key(m[e.key])});
async function load(){try{S.c=m3u(await (await fetch($('m3u').value)).text(),+$('limit').value||100);try{S.e=epg(await (await fetch($('epg').value)).text())}catch(e){S.e=new Map()}$('setup').classList.add('hidden');tune(0);render()}catch(e){alert('Could not load the playlist. Try DEMO LINEUP or check the URLs.')}}
function demo(){let n=['EYEPTV INFORMATION','ABC','NBC','CBS','FOX','PBS','ESPN','THE WEATHER CHANNEL','CNN','TBS','TNT','USA','DISNEY CHANNEL','NICKELODEON','CARTOON NETWORK','SKYLINE3'];S.c=n.map((name,i)=>({id:String(i+1),name,url:''}));S.e=new Map();let b=new Date();b.setMinutes(0,0,0);S.c.forEach((c,i)=>S.e.set(c.id,[...Array(8)].map((_,h)=>({start:new Date(b-0+h*36e5),stop:new Date(b+(h+1)*36e5),title:['Local News','Tonight','Movie','SportsCenter','Local Forecast','Programming'][i%6],desc:'EyePTV demonstration programming.'}))));tune(0);render()}demo();
