const $=x=>document.getElementById(x),S={channels:[],epg:new Map(),i:0,last:0,guide:false,info:false,hls:null,phls:null,digits:""};
const now=()=>new Date(),clock=d=>d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#39;"}[c]));
async function get(u){let r=await fetch(u,{cache:"no-store"});if(!r.ok)throw Error(r.status+" "+r.statusText);return r.text()}
function attrs(l){let o={};for(let m of l.matchAll(/([\w-]+)="([^"]*)"/g))o[m[1]]=m[2];return o}
function parseM3U(t,lim){let out=[],meta=null;for(let l of t.split(/\r?\n/)){l=l.trim();if(l.startsWith("#EXTINF")){meta=attrs(l);let n=l.indexOf(",");meta.name=n>=0?l.slice(n+1).trim():(meta["tvg-name"]||"Channel")}else if(l&&!l.startsWith("#")&&meta){out.push({id:meta["tvg-id"]||meta["tvg-name"]||meta.name,name:meta.name,group:meta["group-title"]||"General",url:l});meta=null;if(out.length>=lim)break}}return out}
function xdate(s){if(!s)return null;let m=s.match(/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/);return m?new Date(Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+m[6])):new Date(s)}
function parseEPG(t){let d=new DOMParser().parseFromString(t,"application/xml"),m=new Map();for(let p of d.querySelectorAll("programme")){let id=p.getAttribute("channel"),s=xdate(p.getAttribute("start")),e=xdate(p.getAttribute("stop"));if(!id||!s||!e)continue;let q={start:s,stop:e,title:p.querySelector("title")?.textContent.trim()||"Programming",desc:p.querySelector("desc")?.textContent.trim()||""};if(!m.has(id))m.set(id,[]);m.get(id).push(q)}return m}
function prog(c){let a=S.epg.get(c.id)||S.epg.get(c.name)||[],t=now();return a.find(p=>p.start<=t&&p.stop>t)||a[0]}
function render(){ $("guideClock").textContent=clock(now());$("guideDay").textContent=now().toLocaleDateString([],{weekday:"short",month:"short",day:"numeric"}).toUpperCase();let b=$("rows");b.innerHTML="";S.channels.slice(0,8).forEach((c,i)=>{let p=prog(c),r=document.createElement("div");r.className="row"+(i===S.i?" sel":"");r.innerHTML=`<div class="num">${String(i+1).padStart(3,"0")}</div><div class="rtext"><div class="rname">${esc(c.name)}</div><div class="rprog">${esc(p?.title||"PROGRAM INFORMATION UNAVAILABLE")}</div></div>`;r.onclick=()=>{S.i=i;render();preview()};b.append(r)});preview()}
function preview(){let c=S.channels[S.i];if(!c)return;let p=prog(c);$("pChannel").textContent=`${String(S.i+1).padStart(3,"0")} ${c.name}`;$("pTitle").textContent=p?.title||c.name;$("pDesc").textContent=p?.desc||"Press OK to tune.";if(c.url)playPreview(c.url)}
function playPreview(u){try{let v=$("previewVideo");if(S.phls)S.phls.destroy();if(window.Hls&&Hls.isSupported()){S.phls=new Hls({enableWorker:true});S.phls.loadSource(u);S.phls.attachMedia(v);S.phls.on(Hls.Events.MANIFEST_PARSED,()=>v.play().catch(()=>{}))}else{v.src=u;v.play().catch(()=>{})}}catch(e){}}
function banner(){let c=S.channels[S.i],p=prog(c);$("bn").textContent=String(S.i+1).padStart(3,"0");$("bc").textContent=c.name;$("bt").textContent=p?.title||"Digital Cable";$("bd").textContent=clock(now());$("banner").classList.remove("hidden");clearTimeout(S.bt);S.bt=setTimeout(()=>$("banner").classList.add("hidden"),4200)}
function tune(i){if(!S.channels.length)return;S.last=S.i;S.i=Math.max(0,Math.min(S.channels.length-1,i));let c=S.channels[S.i],v=$("mainVideo");$("guide").classList.add("hidden");S.guide=false;try{if(S.hls)S.hls.destroy();if(c.url&&window.Hls&&Hls.isSupported()){S.hls=new Hls({enableWorker:true});S.hls.loadSource(c.url);S.hls.attachMedia(v);S.hls.on(Hls.Events.MANIFEST_PARSED,()=>v.play().catch(()=>{}))}else if(c.url){v.src=c.url;v.play().catch(()=>{})}}catch(e){}banner()}
function info(){let c=S.channels[S.i],p=prog(c);$("ic").textContent=`${String(S.i+1).padStart(3,"0")} ${c.name}`;$("it").textContent=p?.title||"Digital Cable";$("im").textContent=p?`${clock(p.start)} - ${clock(p.stop)}`:"PROGRAM INFORMATION UNAVAILABLE";$("id").textContent=p?.desc||"No program description available.";$("info").classList.remove("hidden");S.info=true;clearTimeout(S.it);S.it=setTimeout(closeInfo,6500)}
function closeInfo(){$("info").classList.add("hidden");S.info=false}
function key(k){if(S.info){if(k==="exit"||k==="info")closeInfo();return}if(k==="guide"){S.guide=!S.guide;$("guide").classList.toggle("hidden",!S.guide);if(S.guide)render();return}if(k==="info"){info();return}if(k==="exit"){$("guide").classList.add("hidden");S.guide=false;return}if(k==="up"){S.guide?(S.i=Math.max(0,S.i-1),render()):tune(S.i-1);return}if(k==="down"){S.guide?(S.i=Math.min(S.channels.length-1,S.i+1),render()):tune(S.i+1);return}if(k==="chup"){tune(S.i+1);return}if(k==="chdn"){tune(S.i-1);return}if(k==="last"){tune(S.last);return}if(k==="ok"){S.guide?tune(S.i):banner();return}if(/^\d$/.test(k)){S.digits+=k;clearTimeout(S.dt);S.dt=setTimeout(()=>{let n=parseInt(S.digits)-1;S.digits="";if(n>=0&&n<S.channels.length)tune(n)},900)}}
document.querySelectorAll("#remote button").forEach(b=>b.onclick=()=>key(b.dataset.k));
document.addEventListener("keydown",e=>{let k=e.key;if(k==="ArrowUp")key("up");else if(k==="ArrowDown")key("down");else if(k==="Enter")key("ok");else if(k==="Escape")key("exit");else if(k.toLowerCase()==="g")key("guide");else if(k.toLowerCase()==="i")key("info");else if(k.toLowerCase()==="l")key("last");else if(k==="PageUp")key("chup");else if(k==="PageDown")key("chdn");else if(/^\d$/.test(k))key(k)});
async function load(){let lim=Math.min(5000,Math.max(1,+$("limit").value||100));$("status").textContent="Downloading IPTV-org M3U…";try{let t=await get($("m3u").value.trim());S.channels=parseM3U(t,lim);if(!S.channels.length)throw Error("No channels parsed");$("status").textContent=`Parsed ${S.channels.length} channels. Downloading EPG…`;try{S.epg=parseEPG(await get($("epg").value.trim()))}catch(e){S.epg=new Map();$("status").textContent+=" EPG unavailable."} $("setup").classList.add("hidden");tune(0);toast(`IPTV LINEUP LOADED • ${S.channels.length} CHANNELS`)}catch(e){$("status").textContent="LOAD FAILED: "+e.message;toast("IPTV LOAD FAILED")}}
function demo(){let n=["eyePTV INFORMATION","ABC","NBC","CBS","FOX","PBS","ESPN","THE WEATHER CHANNEL","CNN","TBS","TNT","USA","DISNEY CHANNEL","NICKELODEON","CARTOON NETWORK","SKYLINE3"];S.channels=n.map((name,i)=>({id:String(i+1),name,url:""}));S.epg=new Map();let b=new Date();b.setMinutes(0,0,0);S.channels.forEach((c,i)=>S.epg.set(c.id,Array.from({length:8},(_,h)=>({start:new Date(b.getTime()+h*3600000),stop:new Date(b.getTime()+(h+1)*3600000),title:["Local News","Tonight","Movie","SportsCenter","Local Forecast","Programming"][i%6],desc:"eyePTV demonstration programming."}))));tune(0)}
function toast(t){$("toast").textContent=t;$("toast").style.display="block";clearTimeout(window.tt);window.tt=setTimeout(()=>$("toast").style.display="none",3000)}
$("load").onclick=load;$("demo").onclick=demo;demo();
